services:
  nestjs:
    depends_on:
      database:
        condition: service_healthy
    restart: &restartpolicy unless-stopped

  database:
    image: postgres:latest
    restart: *restartpolicy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localuser -d localdb"]
      interval: 10s
      timeout: 5s
      retries: 5
