services:
  nestjs:
    build:
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avento_origin
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/avento_origin?schema=public
    ports:
      - "4000:4000"

  database:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avento_origin
